In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import requests
from google.colab import files
 
 
uploaded = files.upload()

Saving campeones.csv to campeones.csv

In [2]:
campeones = pd.read_csv ("campeones.csv")
campeones.head(2)

,Unnamed: 0,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,...,rng,ID,Dificultad,AD,Defensa,AP,Pasiva,Win Rate,Ban Rate,Play Rate
0,0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,...,175.0,266,4,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 6.409201647077534, <Po..."
1,1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,...,550.0,103,5,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.01662414984586634, <..."

In [3]:
campeones = campeones.drop(["Unnamed: 0"], axis=1)
campeones.head(2)

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,rng,ID,Dificultad,AD,Defensa,AP,Pasiva,Win Rate,Ban Rate,Play Rate
0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,60.00,...,175.0,266,4,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 6.409201647077534, <Po..."
1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,53.04,...,550.0,103,5,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.01662414984586634, <..."

Eliminamos la primera columna inservible como hemos visto en en an√°lisis de datos previo

In [4]:
campeones = campeones.drop(["Win Rate"], axis=1)
campeones.head(2)

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,ms,rng,ID,Dificultad,AD,Defensa,AP,Pasiva,Ban Rate,Play Rate
0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,60.00,...,345.0,175.0,266,4,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 6.409201647077534, <Po..."
1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,53.04,...,330.0,550.0,103,5,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.0, <Position.jungle:...","{<Position.top: 'TOP'>: 0.01662414984586634, <..."

In [5]:
campeones = campeones.drop(["Ban Rate"], axis=1)
campeones.head(2)

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,mr+,ms,rng,ID,Dificultad,AD,Defensa,AP,Pasiva,Play Rate
0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,60.00,...,1.25,345.0,175.0,266,4,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 6.409201647077534, <Po..."
1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,53.04,...,0.50,330.0,550.0,103,5,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.01662414984586634, <..."

Eliminamos win y ban rate debido a que nos devuelve todos los valores con ceros

In [52]:
comprobacion = campeones.loc[145, "Play Rate"]

In [7]:
comprobacion

"{<Position.top: 'TOP'>: 0.0, <Position.jungle: 'JUNGLE'>: 0.0, <Position.middle: 'MIDDLE'>: 0.12043501745921743, <Position.bottom: 'BOTTOM'>: 0.005867347004423413, <Position.utility: 'UTILITY'>: 4.207376747755289}"

x

Pasamos a comprobar que nos devuelve el objeto contenido en "Play Rate" para ver c√≥mo podemos manejarlo y extraer el dato. Es un string con car√°cteres raros que puede parecer que tiene diccionarios dentro, pero no es as√≠. Procedemos a explorar c√≥mo acceder al dato

In [8]:
separada = comprobacion.split(",")
separada

["{<Position.top: 'TOP'>: 0.0",
 " <Position.jungle: 'JUNGLE'>: 0.0",
 " <Position.middle: 'MIDDLE'>: 0.12043501745921743",
 " <Position.bottom: 'BOTTOM'>: 0.005867347004423413",
 " <Position.utility: 'UTILITY'>: 4.207376747755289}"]

In [9]:
comprobacion2 = separada[0]
comprobacion2

"{<Position.top: 'TOP'>: 0.0"

In [10]:
comprobacion3 = comprobacion2.replace("<", "") and comprobacion2.replace(">", "") and comprobacion2.replace("{<", "")

In [11]:
comprobacion4 = comprobacion3.split(":", 1) 
comprobacion5 = comprobacion4[1]

In [12]:
comprobacion5 = comprobacion5.replace(">", "") and comprobacion5.replace(" ", "") and comprobacion5.replace("' '", "") 
comprobacion6 = comprobacion5.split(":")
comprobacion6

[" 'TOP'>", ' 0.0']

In [14]:
float(comprobacion6[1])

0.0

Lo tenemos. Tenemos el camino para acceder al rato y nos deja convertirlo a float para trabajar con √©l. Pasamos a la acci√≥n

In [15]:
campeones.insert(26,"TOP Play Rate","")
campeones.insert(27,"Jungle Play Rate","")
campeones.insert(28,"MID Play Rate","")
campeones.insert(29,"ADC Play Rate","")
campeones.insert(30,"Support Play Rate","")

Creamos columnas vac√≠as para todos los rates que vamos a extraer separados por posici√≥n.

In [18]:
campeones.head(2)

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,AD,Defensa,AP,Pasiva,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,60.00,...,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 6.409201647077534, <Po...",,,,,
1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,53.04,...,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.01662414984586634, <...",,,,,

In [24]:
for i in range (0, 146):
    iter1 = campeones.loc[i, "Play Rate"]
    iter2 = iter1.split(",")
    iter3 = iter2[4]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "") and iter3.replace("}", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    print(iter9)

0.0
0.11572569946882497
0.0003088077370749165
6.731751328452285
0.0009006892331351731
0.37476392291850075
0.25896102151540706
0.5040514288405324
0.0
0.0
4.051325904620098
5.664228715362387
3.6648272876927503
3.1669005456375374
0.0
0.01441102773016277
0.0007205513865081385
0.04428817629216094
0.0
0.0
0.00028307375898534013
0.0911754843713691
0.0
0.00028307375898534013
0.009006892331351731
0.0
0.011400152293682334
0.2711074591736871
0.0
0.0010550931016726315
1.8988587752736614
0.0
0.0
0.0
0.6308684728659648
0.0
0.0
0.15306570167680028
0.0
0.0
0.02550237228677019
5.266021138404282
0.11335817348458394
0.0
0.0
0.0
0.0
0.0003345417151644929
0.0
12.613663764474397
0.019840897107063386
0.0
0.0
0.011451620249861487
0.0
0.015157313094760485
0.0
0.0
0.0009006892331351731
0.0008492212769560204
0.16104323488456895
0.1002081106808104
11.220966604244614
0.010834004775711654
0.0
17.22300524998887
5.594901378389069
0.3873735721823932
0.003474087042092811
2.744297157450514
0.0
0.22411721518212066
0.0006690834303289858
7.130550786906449
5.111308462129749
0.02164227557333373
10.287157741308157
0.4960996296108533
0.02050998053739237
0.0
0.07455133452550275
0.0
0.09822659436791302
0.02413847144802264
1.8063708580197242
0.32936918556848804
6.720943057654662
0.0017499105100911934
0.0
3.523110270353454
0.079517992296791
0.0003088077370749165
0.0
0.000411743649433222
0.0
0.10787683615150416
0.0
0.0007205513865081385
12.427298295149686
1.5447335027830011
0.45505393455797905
0.0
0.005404135398811039
0.09086667663429418
0.0
0.0
2.177351886159057
4.866835670278773
2.7068027513740014
0.09907581564486903
0.07460280248168191
0.3465080149761459
0.15414652875656248
0.0
1.131162740905419
0.1497974864594241
16.98720480875408
0.0
0.15013202817458857
0.0
0.0003088077370749165
0.4903352185187882
0.0
0.0
0.000411743649433222
0.0
0.715121517131238
1.9134242068723617
0.000617615474149833
0.0
0.0
0.0030108754364804357
0.0
0.10069705626451235
0.0
5.167537204255473
0.012043501745921743
0.0
0.0
11.169498648065462
0.3700288709500187
0.0
0.23291823568875578
3.9296556562125815
0.08000693788049296
4.207376747755289

Concatenamos todo el proceso investigado antes y vemos que funciona

In [19]:
def extraer_top (celda):
    iter2 = celda.split(",")
    iter3 = iter2[0]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "") and iter3.replace("{<", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    return iter9

Procedemos a montar una funci√≥n para cada rate a extraer por posici√≥n contando con sus variaciones para la limpieza dependiendo de la posici√≥n donde se encuentre el dato

In [20]:
def extraer_jungla (celda):
    iter2 = celda.split(",")
    iter3 = iter2[1]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    return iter9

In [21]:
def extraer_mid (celda):
    iter2 = celda.split(",")
    iter3 = iter2[2]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    return iter9

In [22]:
def extraer_adc (celda):
    iter2 = celda.split(",")
    iter3 = iter2[3]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    return iter9

In [23]:
def extraer_support (celda):
    iter2 = celda.split(",")
    iter3 = iter2[4]
    iter4 = iter3.replace("<", "") and iter3.replace(">", "") and iter3.replace("}", "")
    iter5 = iter4.split(":", 1)
    iter6 = iter5[1]
    iter7 = iter6.replace(">", "") and iter6.replace(" ", "") and iter6.replace("' '", "") 
    iter8 = iter7.split(":")
    iter9 = float(iter8[1])
    return iter9

In [25]:
campeones["TOP Play Rate"] = campeones["Play Rate"].apply(extraer_top)
campeones["Jungle Play Rate"] = campeones["Play Rate"].apply(extraer_jungla)
campeones["MID Play Rate"] = campeones["Play Rate"].apply(extraer_mid)
campeones["ADC Play Rate"] = campeones["Play Rate"].apply(extraer_adc)
campeones["Support Play Rate"] = campeones["Play Rate"].apply(extraer_support)

Una vez montadas todas las funciones, las aplicamos sobre la columnna que recoge todos los play rates y e incluimos los valores en la columna que le corresponde a cada uno

In [26]:
comparativa = campeones.head(5).copy()

Creamos una copia del df original para ver c√≥mo hacemos para comparar entre columnas

In [27]:
comparativa

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,AD,Defensa,AP,Pasiva,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.00,90.0,3.0,1.00,0.0,0.0,0.000,0.000,60.0000,...,8,4,3,Deathbringer Stance,"{<Position.top: 'TOP'>: 6.409201647077534, <Po...",6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,526.00,92.0,6.5,0.60,418.0,25.0,8.000,0.800,53.0400,...,3,4,8,Essence Theft,"{<Position.top: 'TOP'>: 0.01662414984586634, <...",0.016624,0.000000,4.514049,0.006099,0.115726
2,Akali,575.00,95.0,8.0,0.50,200.0,0.0,50.000,0.000,62.4000,...,5,3,8,Assassin's Mark,"{<Position.top: 'TOP'>: 4.308408345734966, <Po...",4.308408,0.000000,10.976777,0.000000,0.000309
3,Alistar,573.36,106.0,8.5,0.85,350.0,40.0,8.500,0.800,61.1116,...,6,9,5,Triumphant Roar,"{<Position.top: 'TOP'>: 0.00319101328310747, <...",0.003191,0.000000,0.000000,0.000000,6.731751
4,Amumu,613.12,84.0,9.0,0.85,287.2,40.0,7.382,0.525,53.3800,...,2,6,8,Cursed Touch,"{<Position.top: 'TOP'>: 0.0029336735022117066,...",0.002934,1.941346,0.000000,0.000000,0.000901

In [28]:
comparativa.columns

Index(['name', 'hp', 'hp+', 'hp5', 'hp5+', 'mp', 'mp+', 'mp5', 'mp5+', 'ad',
       'ad+', 'as', 'as+', 'ar', 'ar+', 'mr', 'mr+', 'ms', 'rng', 'ID',
       'Dificultad', 'AD', 'Defensa', 'AP', 'Pasiva', 'Play Rate',
       'TOP Play Rate', 'Jungle Play Rate', 'MID Play Rate', 'ADC Play Rate',
       'Support Play Rate'],
      dtype='object')

In [29]:
comparativa.iloc[:, -5:]

,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,6.409202,0.018245,0.349107,0.000000,0.000000
1,0.016624,0.000000,4.514049,0.006099,0.115726
2,4.308408,0.000000,10.976777,0.000000,0.000309
3,0.003191,0.000000,0.000000,0.000000,6.731751
4,0.002934,1.941346,0.000000,0.000000,0.000901

In [30]:
comparativa = campeones.iloc[:, -5:].copy()

In [31]:
comparativa.head(5)

,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,6.409202,0.018245,0.349107,0.000000,0.000000
1,0.016624,0.000000,4.514049,0.006099,0.115726
2,4.308408,0.000000,10.976777,0.000000,0.000309
3,0.003191,0.000000,0.000000,0.000000,6.731751
4,0.002934,1.941346,0.000000,0.000000,0.000901

In [32]:
campeones.insert(25,"Posicion","")

Columna nueva para, ejecutando la siguiente funci√≥n, asignar posici√≥n preferente a cada campe√≥n

In [33]:
def cutrez (data, col1, col2, col3, col4, col5, col6, val1, val2, val3, val4, val5):
  for i in data.index:
    if (data[col1][i]) > (data[col2][i]) and (data[col1][i]) > (data[col3][i]) and (data[col1][i]) > (data[col4][i]) and (data[col1][i]) > (data[col5][i]):
      data.loc[i, col6]=val1
    elif (data[col2][i]) > (data[col1][i]) and (data[col2][i]) > (data[col3][i]) and (data[col2][i]) > (data[col4][i]) and (data[col2][i]) > (data[col5][i]):
      data.loc[i, col6]=val2
    elif (data[col3][i]) > (data[col1][i]) and (data[col3][i]) > (data[col2][i]) and (data[col3][i]) > (data[col4][i]) and (data[col3][i]) > (data[col5][i]):
      data.loc[i, col6]=val3    
    elif (data[col4][i]) > (data[col1][i]) and (data[col4][i]) > (data[col2][i]) and (data[col4][i]) > (data[col3][i]) and (data[col4][i]) > (data[col5][i]):
      data.loc[i, col6]=val4
    elif (data[col5][i]) > (data[col1][i]) and (data[col5][i]) > (data[col2][i]) and (data[col5][i]) > (data[col3][i]) and (data[col5][i]) > (data[col4][i]):
      data.loc[i, col6]=val5

Funci√≥n, por la cual pido perd√≥n de antemano, que lo que hace es buscar, por campe√≥n, en cu√°l posici√≥n tiene mayor Play Rate para saber a qu√© posici√≥n pertenece cada campe√≥n de forma preferente

In [34]:
cutrez (campeones, "TOP Play Rate", "Jungle Play Rate", "MID Play Rate", "ADC Play Rate", "Support Play Rate", "Posicion", "TOP", "Jungle", "MID", "ADC", "Support")

Ejecutamos la funci√≥n anterior

In [35]:
campeones.head(2)

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,Defensa,AP,Pasiva,Posicion,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.0,90.0,3.0,1.0,0.0,0.0,0.0,0.0,60.00,...,4,3,Deathbringer Stance,TOP,"{<Position.top: 'TOP'>: 6.409201647077534, <Po...",6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,526.0,92.0,6.5,0.6,418.0,25.0,8.0,0.8,53.04,...,4,8,Essence Theft,MID,"{<Position.top: 'TOP'>: 0.01662414984586634, <...",0.016624,0.000000,4.514049,0.006099,0.115726

In [36]:
def play_rate_total (data, col1, col2, col3, col4, col5, col6):
  for i in data.index:
    data.loc[i, col1] = data.loc[i, col2] + data.loc[i, col3] + data.loc[i, col4] + data.loc[i, col5] + data.loc[i, col6]

Montamos una funci√≥n que sume todos los play rates para poder ver el play rate total de cada campe√≥n, ver qu√© campeones son los m√°s usados

In [37]:
play_rate_total (campeones, "Play Rate", "TOP Play Rate", "Jungle Play Rate", "MID Play Rate", "ADC Play Rate", "Support Play Rate")

Ejecutamos

In [38]:
campeones

,name,hp,hp+,hp5,hp5+,mp,mp+,mp5,mp5+,ad,...,Defensa,AP,Pasiva,Posicion,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.00,90.0,3.0,1.00,0.0,0.0,0.000,0.000,60.0000,...,4,3,Deathbringer Stance,TOP,6.776554,6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,526.00,92.0,6.5,0.60,418.0,25.0,8.000,0.800,53.0400,...,4,8,Essence Theft,MID,4.652497,0.016624,0.000000,4.514049,0.006099,0.115726
2,Akali,575.00,95.0,8.0,0.50,200.0,0.0,50.000,0.000,62.4000,...,3,8,Assassin's Mark,MID,15.285494,4.308408,0.000000,10.976777,0.000000,0.000309
3,Alistar,573.36,106.0,8.5,0.85,350.0,40.0,8.500,0.800,61.1116,...,9,5,Triumphant Roar,Support,6.734942,0.003191,0.000000,0.000000,0.000000,6.731751
4,Amumu,613.12,84.0,9.0,0.85,287.2,40.0,7.382,0.525,53.3800,...,6,8,Cursed Touch,Jungle,1.94518,0.002934,1.941346,0.000000,0.000000,0.000901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Zed,584.00,85.0,7.0,0.65,200.0,0.0,50.000,0.000,63.0000,...,2,1,Contempt for the Weak,MID,11.882304,0.262821,0.214338,11.399663,0.005481,0.000000
142,Ziggs,536.00,92.0,6.5,0.60,480.0,23.5,8.000,0.800,54.2080,...,4,9,Short Fuse,MID,3.64949,0.000000,0.000000,2.453941,0.962631,0.232918
143,Zilean,504.00,82.0,5.5,0.50,452.0,30.0,11.335,0.800,51.6400,...,5,8,Time In A Bottle,Support,4.401643,0.028899,0.000000,0.437838,0.005250,3.929656
144,Zoe,560.00,92.0,6.5,0.60,425.0,25.0,8.000,0.650,58.0000,...,7,8,More Sparkles!,MID,2.817021,0.003886,0.000000,2.732176,0.000952,0.080007
145,Zyra,504.00,79.0,5.5,0.50,418.0,25.0,13.000,0.400,53.3760,...,3,8,Garden of Thorns,Support,4.333679,0.000000,0.000000,0.120435,0.005867,4.207377

In [39]:
campeones.columns

Index(['name', 'hp', 'hp+', 'hp5', 'hp5+', 'mp', 'mp+', 'mp5', 'mp5+', 'ad',
       'ad+', 'as', 'as+', 'ar', 'ar+', 'mr', 'mr+', 'ms', 'rng', 'ID',
       'Dificultad', 'AD', 'Defensa', 'AP', 'Pasiva', 'Posicion', 'Play Rate',
       'TOP Play Rate', 'Jungle Play Rate', 'MID Play Rate', 'ADC Play Rate',
       'Support Play Rate'],
      dtype='object')

In [40]:
campeones.insert(3,"Total HP","")
campeones.insert(7,"Total Magic Power","")
campeones.insert(12,"Total Attack Damage","")
campeones.insert(14,"Total Attack Speed","")
campeones.insert(16,"Total Attack Resistance","")
campeones.insert(18,"Total Magic Resistance","")

In [41]:
campeones.insert(3,"Incremento HP","")
campeones.insert(7,"Incremento Magic Power","")
campeones.insert(12,"Incremento Attack Damage","")
campeones.insert(14,"Incremento Attack Speed","")
campeones.insert(16,"Incremento Attack Resistance","")
campeones.insert(18,"Incremento Magic Resistance","")

Insertamos columnas para poder almacenar en ellas el total de las estad√≠sticas y el incremento total a nivel m√°ximo de cada estad√≠stica

In [42]:
def incremento (celda):
  valor = celda * 17
  return valor

Funci√≥n para calcular el incremento. PD: Son 18 niveles y se empieza en el 1, por eso multiplicamos por 17

In [43]:
campeones["Incremento HP"] = campeones["hp+"].apply(incremento)
campeones["Incremento Magic Power"] = campeones["mp+"].apply(incremento)
campeones["Incremento Attack Damage"] = campeones["ad+"].apply(incremento)
campeones["Incremento Attack Speed"] = campeones["as+"].apply(incremento)
campeones["Incremento Attack Resistance"] = campeones["ar+"].apply(incremento)
campeones["Incremento Magic Resistance"] = campeones["mr+"].apply(incremento)

Aplicamos para ver incremento de estad√≠sitca para cada campe√≥n

In [44]:
campeones.head(5)

,name,hp,hp+,Incremento HP,Total HP,hp5,hp5+,Incremento Magic Power,mp,Total Magic Power,...,Defensa,AP,Pasiva,Posicion,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.00,90.0,1530.0,,3.0,1.00,0.0,0.0,,...,4,3,Deathbringer Stance,TOP,6.776554,6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,526.00,92.0,1564.0,,6.5,0.60,425.0,418.0,,...,4,8,Essence Theft,MID,4.652497,0.016624,0.000000,4.514049,0.006099,0.115726
2,Akali,575.00,95.0,1615.0,,8.0,0.50,0.0,200.0,,...,3,8,Assassin's Mark,MID,15.285494,4.308408,0.000000,10.976777,0.000000,0.000309
3,Alistar,573.36,106.0,1802.0,,8.5,0.85,680.0,350.0,,...,9,5,Triumphant Roar,Support,6.734942,0.003191,0.000000,0.000000,0.000000,6.731751
4,Amumu,613.12,84.0,1428.0,,9.0,0.85,680.0,287.2,,...,6,8,Cursed Touch,Jungle,1.94518,0.002934,1.941346,0.000000,0.000000,0.000901

In [45]:
def totales (base, incremento):
  for ir in range (0, 145):
    total = base + incremento
    return total

Sumamos estad√≠sticas base e incrementos de las mismas para poder ver el total de cada estad√≠stica a nivel m√°ximo

In [46]:
campeones["Total HP"] = totales (campeones["hp"], campeones["Incremento HP"])
campeones["Total Magic Power"] = totales (campeones["mp"], campeones["Incremento Magic Power"])
campeones["Total Attack Damage"] = totales (campeones["ad"], campeones["Incremento Attack Damage"])
campeones["Total Attack Speed"] = totales (campeones["as"], campeones["Incremento Attack Speed"])
campeones["Total Attack Resistance"] = totales (campeones["ar"], campeones["Incremento Attack Resistance"])
campeones["Total Magic Resistance"] = totales (campeones["mr"], campeones["Incremento Magic Resistance"])

Aplicamos

In [47]:
campeones.head(5)

,name,hp,hp+,Incremento HP,Total HP,hp5,hp5+,Incremento Magic Power,mp,Total Magic Power,...,Defensa,AP,Pasiva,Posicion,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,580.00,90.0,1530.0,2110.00,3.0,1.00,0.0,0.0,0.0,...,4,3,Deathbringer Stance,TOP,6.776554,6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,526.00,92.0,1564.0,2090.00,6.5,0.60,425.0,418.0,843.0,...,4,8,Essence Theft,MID,4.652497,0.016624,0.000000,4.514049,0.006099,0.115726
2,Akali,575.00,95.0,1615.0,2190.00,8.0,0.50,0.0,200.0,200.0,...,3,8,Assassin's Mark,MID,15.285494,4.308408,0.000000,10.976777,0.000000,0.000309
3,Alistar,573.36,106.0,1802.0,2375.36,8.5,0.85,680.0,350.0,1030.0,...,9,5,Triumphant Roar,Support,6.734942,0.003191,0.000000,0.000000,0.000000,6.731751
4,Amumu,613.12,84.0,1428.0,2041.12,9.0,0.85,680.0,287.2,967.2,...,6,8,Cursed Touch,Jungle,1.94518,0.002934,1.941346,0.000000,0.000000,0.000901

Una vez hemos calculado todo esto, procedemos a eliminar las celdas de valores base e incremento por nivel para limpiar el dataframe.

In [48]:
campeones = campeones.drop(["hp"], axis=1)
campeones = campeones.drop(["hp+"], axis=1)
campeones = campeones.drop(["hp5"], axis=1)
campeones = campeones.drop(["hp5+"], axis=1)
campeones = campeones.drop(["mp"], axis=1)
campeones = campeones.drop(["mp+"], axis=1)
campeones = campeones.drop(["mp5"], axis=1)
campeones = campeones.drop(["mp5+"], axis=1)
campeones = campeones.drop(["ad"], axis=1)
campeones = campeones.drop(["ad+"], axis=1)
campeones = campeones.drop(["as"], axis=1)
campeones = campeones.drop(["as+"], axis=1)
campeones = campeones.drop(["ar"], axis=1)
campeones = campeones.drop(["ar+"], axis=1)
campeones = campeones.drop(["mr"], axis=1)
campeones = campeones.drop(["mr+"], axis=1)

In [49]:
campeones

,name,Incremento HP,Total HP,Incremento Magic Power,Total Magic Power,Incremento Attack Damage,Incremento Attack Speed,Incremento Attack Resistance,Total Attack Damage,Incremento Magic Resistance,...,Defensa,AP,Pasiva,Posicion,Play Rate,TOP Play Rate,Jungle Play Rate,MID Play Rate,ADC Play Rate,Support Play Rate
0,Aatrox,1530.0,2110.00,0.0,0.0,85.00,42.500,55.25,145.0000,21.25,...,4,3,Deathbringer Stance,TOP,6.776554,6.409202,0.018245,0.349107,0.000000,0.000000
1,Ahri,1564.0,2090.00,425.0,843.0,51.00,34.000,59.50,104.0400,8.50,...,4,8,Essence Theft,MID,4.652497,0.016624,0.000000,4.514049,0.006099,0.115726
2,Akali,1615.0,2190.00,0.0,200.0,56.10,54.400,59.50,118.5000,21.25,...,3,8,Assassin's Mark,MID,15.285494,4.308408,0.000000,10.976777,0.000000,0.000309
3,Alistar,1802.0,2375.36,680.0,1030.0,61.54,36.125,59.50,122.6516,21.25,...,9,5,Triumphant Roar,Support,6.734942,0.003191,0.000000,0.000000,0.000000,6.731751
4,Amumu,1428.0,2041.12,680.0,967.2,64.60,37.060,64.60,117.9800,21.25,...,6,8,Cursed Touch,Jungle,1.94518,0.002934,1.941346,0.000000,0.000000,0.000901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Zed,1445.0,2029.00,0.0,200.0,57.80,56.100,59.50,120.8000,21.25,...,2,1,Contempt for the Weak,MID,11.882304,0.262821,0.214338,11.399663,0.005481,0.000000
142,Ziggs,1564.0,2100.00,399.5,879.5,52.70,34.000,56.10,106.9080,8.50,...,4,9,Short Fuse,MID,3.64949,0.000000,0.000000,2.453941,0.962631,0.232918
143,Zilean,1394.0,1898.00,510.0,962.0,51.00,36.210,64.60,102.6400,8.50,...,5,8,Time In A Bottle,Support,4.401643,0.028899,0.000000,0.437838,0.005250,3.929656
144,Zoe,1564.0,2124.00,425.0,850.0,56.10,42.500,59.50,114.1000,8.50,...,7,8,More Sparkles!,MID,2.817021,0.003886,0.000000,2.732176,0.000952,0.080007
145,Zyra,1343.0,1847.00,425.0,843.0,54.40,35.870,51.00,107.7760,8.50,...,3,8,Garden of Thorns,Support,4.333679,0.000000,0.000000,0.120435,0.005867,4.207377

In [50]:
campeones.to_csv("campeones_definitivo.csv")

In [51]:
from google.colab import files
files.download("campeones_definitivo.csv")

Sacamos y descargamos nuestro nuevo dataframe